### ISSUE TITLE
[Question] Can i add an `index()` on `foreignIdFor()`?

### ISSUE THREAD

**Issue by juliomotol** [planetscale/laravel-example#7]
https://github.com/planetscale/laravel-example/blob/5fc6582323e063fefb2d0acb12b0cad9354343a1/database/migrations/2021_12_20_194637_create_stars_table.php#L16-L20

Wouldn't it be better to add an `index()` on the `foreignIdFor()`?

```php
$table->foreignId('constellation_id')->index();
```

**Comment by aarondfrancis** [comment]
Yes! Added in https://github.com/planetscale/laravel-example/pull/8. Thank you for the suggestion 🤝
